[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "genmanip-client"
version = "0.1.2"
description = "Python client for GenManip eval server"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "GenManip-Sim contributors" }]
dependencies = ["requests>=2.0.0"]

[project.optional-dependencies]
full_numpy1 = [
    "Pillow>=9.0.0", "torch>=2.0.0", "matplotlib", "PyTurboJPEG",
    "numpy<2",
    "opencv-python<4.12",
]
full_numpy2 = [
    "Pillow>=9.0.0", "torch>=2.0.0", "matplotlib", "PyTurboJPEG",
    "numpy>=2",
    "opencv-python>=4.12",
]

[project.scripts]
genmanip-client = "genmanip_client.cli:main_legacy"
gmp = "genmanip_client.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

